/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package salaba;

import com.querydsl.jpa.impl.JPAQueryFactory;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.data.domain.AuditorAware;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;
import salaba.exception.CannotFindMemberException;
import salaba.service.InitService;
import salaba.interceptor.MemberContextHolder;

import javax.annotation.PostConstruct;
import javax.persistence.EntityManager;
import java.util.Optional;

@SpringBootApplication
@EnableJpaAuditing
@RequiredArgsConstructor
public class App {
    private final InitService initService;

    public static void main(String[] args) throws Exception {
        SpringApplication.run(App.class, args);
    }

    @PostConstruct
    public void init() {
        initService.init();
    }

//    @Bean
//    public AuditorAware<String> auditorProvider() {
//        try {
//            return () -> Optional.of(MemberContextHolder.getMemberId().toString());
//        } catch (CannotFindMemberException e) {
//            return () -> Optional.of("new");
//        }
//
//    }

    @Bean
    public JPAQueryFactory jpaQueryFactory(EntityManager entityManager) {
        return new JPAQueryFactory(entityManager);
    }

}
