spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

management:
  endpoint:
    warm-up:
      enable: true
      times: 3

